# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        # bind:
        #    $app: '@vbo.app'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/boxoffice/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    Silex\Application:
        arguments:
            - '@service_container'

    vbo.app: '@Silex\Application'

    Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler:
        arguments:
            - '%env(DATABASE_URL)%'
            - { lock_mode: 1 }

    vbo.url_generator:
        alias: 'Symfony\Component\Routing\Generator\UrlGeneratorInterface'
        public: true

    vbo.permission_check:
        alias: 'App\Conveniences\Permissions'
        public: true

    vbo.dateformat:
        alias: 'App\Conveniences\Dateformat'
        public: true

    App\Controller\:
        resource: '../src/Controller/'
        tags: [ 'controller.service_arguments' ]
    
    EZPZTicketing\BoxOffice\Addons\ProgressBookVL\StudentFeesController:
        tags: [ 'controller.service_arguments' ]

    EZPZTicketing\BoxOffice\AdminAccountsController:
        tags: [ 'controller.service_arguments' ]

    EZPZTicketing\BoxOffice\AdminBlacklistController:
        tags: [ 'controller.service_arguments' ]

    EZPZTicketing\BoxOffice\AdminCheckinControllerSite:
        tags: [ 'controller.service_arguments' ]

    EZPZTicketing\BoxOffice\AdminController:
        tags: [ 'controller.service_arguments' ]

    EZPZTicketing\BoxOffice\AdminControllerSite:
        tags: [ 'controller.service_arguments' ]

    EZPZTicketing\BoxOffice\AdminCustomFieldsController:
        tags: [ 'controller.service_arguments' ]

    EZPZTicketing\BoxOffice\AdminDepartmentsControllerSite:
        tags: [ 'controller.service_arguments' ]

    EZPZTicketing\BoxOffice\AdminEventsController:
        tags: [ 'controller.service_arguments' ]

    EZPZTicketing\BoxOffice\AdminEventsControllerSite:
        tags: [ 'controller.service_arguments' ]

    EZPZTicketing\BoxOffice\AdminEventsImportControllerSite:
        tags: [ 'controller.service_arguments' ]

    EZPZTicketing\BoxOffice\AdminMetadataController:
        tags: [ 'controller.service_arguments' ]

    EZPZTicketing\BoxOffice\AdminOrdersControllerSite:
        tags: [ 'controller.service_arguments' ]

    EZPZTicketing\BoxOffice\AdminPaymentModule:
        tags: [ 'controller.service_arguments' ]

    EZPZTicketing\BoxOffice\AdminProductsController:
        tags: [ 'controller.service_arguments' ]

    EZPZTicketing\BoxOffice\AdminProductsControllerSite:
        tags: [ 'controller.service_arguments' ]

    EZPZTicketing\BoxOffice\AdminPromocodeControllerSite:
        tags: [ 'controller.service_arguments' ]

    EZPZTicketing\BoxOffice\AdminReportsControllerSite:
        tags: [ 'controller.service_arguments' ]

    EZPZTicketing\BoxOffice\AdminSchoolsControllerSite:
        tags: [ 'controller.service_arguments' ]

    EZPZTicketing\BoxOffice\AdminSeasonPassesControllerSite:
        tags: [ 'controller.service_arguments' ]

    EZPZTicketing\BoxOffice\AdminSeasonTicketControllerSite:
        tags: [ 'controller.service_arguments' ]

    EZPZTicketing\BoxOffice\AdminSeatingChartsControllerSite:
        tags: [ 'controller.service_arguments' ]

    EZPZTicketing\BoxOffice\AdminSettingsControllerSite:
        tags: [ 'controller.service_arguments' ]

    EZPZTicketing\BoxOffice\AdminStatsControllerSite:
        tags: [ 'controller.service_arguments' ]

    EZPZTicketing\BoxOffice\AdminTicketDesignsController:
        tags: [ 'controller.service_arguments' ]

    EZPZTicketing\BoxOffice\AdminTicketPriceSeatingControllerSite:
        tags: [ 'controller.service_arguments' ]

    EZPZTicketing\BoxOffice\AdminTicketsControllerSite:
        tags: [ 'controller.service_arguments' ]

    EZPZTicketing\BoxOffice\AdminTileEmbedControllerSite:
        tags: [ 'controller.service_arguments' ]

    EZPZTicketing\BoxOffice\AdminVenuesControllerSite:
        tags: [ 'controller.service_arguments' ]

    EZPZTicketing\BoxOffice\ApiControllerSite:
        tags: [ 'controller.service_arguments' ]

    EZPZTicketing\BoxOffice\EmbedControllerSite:
        tags: [ 'controller.service_arguments' ]

    EZPZTicketing\BoxOffice\GuestListNotificationController:
        tags: [ 'controller.service_arguments' ]

    EZPZTicketing\BoxOffice\LoginController:
        tags: [ 'controller.service_arguments' ]

    EZPZTicketing\BoxOffice\Login\HomeTownLoginController:
        tags: [ 'controller.service_arguments' ]

    EZPZTicketing\BoxOffice\NotificationsController:
        tags: [ 'controller.service_arguments' ]

    EZPZTicketing\BoxOffice\Payment\Bluefin\BluefinDeviceController:
        tags: [ 'controller.service_arguments' ]

    EZPZTicketing\BoxOffice\ShareTicketsControllerSite:
        tags: [ 'controller.service_arguments' ]

    EZPZTicketing\BoxOffice\StripeTerminalController:
        tags: [ 'controller.service_arguments' ]

    EZPZTicketing\BoxOffice\TicketingControllerSite:
        tags: [ 'controller.service_arguments' ]
